export { default as Home } from "./Home";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Success } from "./Success";
export { default as Error } from "./Error";
export { default as ShoppingCart } from "./ShoppingCart";
export { default as UserProfile } from "./UserProfile";
export { default as ProductPage } from "./ProductPage";
export { default as AddWork } from "./AddWork";
